
# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 7
# Label requiring a response
responseRequiredLabel: "Up For Grabs"
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  Closing as stale.
