using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliant(true)]
[assembly: AssemblyVersionAttribute("4.0.0")]
[assembly: AssemblyFileVersionAttribute("4.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright Jimmy Bogard 2008-2015")]
[assembly: AssemblyProductAttribute("AutoMapper")]
[assembly: AssemblyTrademarkAttribute("AutoMapper")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("fdd56f8abf45dc625e5edcb36dc881d14c4313c4")]
