name: Release

on:
  push:
    tags:
    - '*.*.*'
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
    - name: Push to MyGet
      env:
        NUGET_URL: https://www.myget.org/F/automapperdev/api/v3/index.json
        NUGET_API_KEY: ${{ secrets.MYGET_CI_API_KEY }}
      run: ./Push.ps1
      shell: pwsh
    - name: Push to NuGet
      env:
        NUGET_URL: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: ./Push.ps1
      shell: pwsh
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/**/*